In [14]:
import pandas as pd

data = pd.read_csv("Dataset2.csv")
data

   Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data["Outlook"] = le.fit_transform(data["Outlook"])
data["Temp"] = le.fit_transform(data["Temp"])
data["Wind"] = le.fit_transform(data["Wind"])

data

    Outlook  Temp  Wind  Humidity  Class
0         1     1     0         1      0
1         1     1     1         2      0
2         0     1     0         1      1
3         1     2     0         1      1
4         2     0     0         1      1
5         0     0     1         0      0
6         0     0     1         1      1
7         1     2     0         1      0
8         0     0     0         0      1
9         2     2     0         2      1
10        1     0     1         2      0
11        0     2     1         0      1
12        0     1     0         1      1
13        2     2     1         1      0

In [16]:
X = data.iloc[:,:4]
Y = data.iloc[:,4:]

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test =  train_test_split(X,Y, random_state=33, test_size=0.1)

In [18]:
from sklearn.naive_bayes import CategoricalNB

In [19]:
cmodel = CategoricalNB()

cmodel.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

CategoricalNB()

In [20]:
y_pred = cmodel.predict(X_test)

In [21]:
Y_test

    Class
0       0
12      1

In [22]:
cmodel.predict([[2,0,1,2]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(

array([0])

In [23]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

print(accuracy_score(Y_test, y_pred), precision_score(Y_test, y_pred), recall_score(Y_test, y_pred))

0.5 0.5 1.0

In [24]:
cmodel.predict_proba(X_test)

array([[0.41774972, 0.58225028],
       [0.12548801, 0.87451199]])

In [25]:
confusion_matrix(Y_test, y_pred)

array([[0, 1],
       [0, 1]])