In [102]:
import pandas as pd
import numpy as np
data = pd.read_csv("Exercise-CarData.csv")
data.head(3)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165

### understand the data

In [103]:
#may perfrom price prediction

data.describe()

,Unnamed: 0,Price,Age,MetColor,Automatic,CC,Weight
count,1436.000000,1436.000000,1336.000000,1286.000000,1436.000000,1436.000000,1436.00000
mean,717.500000,10730.824513,55.672156,0.674961,0.055710,1566.827994,1072.45961
std,414.681806,3626.964585,18.589804,0.468572,0.229441,187.182436,52.64112
min,0.000000,4350.000000,1.000000,0.000000,0.000000,1300.000000,1000.00000
25%,358.750000,8450.000000,43.000000,0.000000,0.000000,1400.000000,1040.00000
50%,717.500000,9900.000000,60.000000,1.000000,0.000000,1600.000000,1070.00000
75%,1076.250000,11950.000000,70.000000,1.000000,0.000000,1600.000000,1085.00000
max,1435.000000,32500.000000,80.000000,1.000000,1.000000,2000.000000,1615.00000

In [104]:

data = data.iloc[:, 1:]
data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,NaN,20544,Petrol,86,1.0,0,1300,3,1025
1432,10845,72.0,??,Petrol,86,0.0,0,1300,3,1015
1433,8500,NaN,17016,Petrol,86,0.0,0,1300,3,1015
1434,7250,70.0,??,NaN,86,1.0,0,1300,3,1015
1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

### Handle Missing Values

In [105]:
data.isnull().sum()

Price          0
Age          100
KM             0
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

age handle

In [106]:
data["Age"] =  data["Age"].fillna(round(data["Age"].mean())).astype("Int16")
data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23,46986,Diesel,90,1.0,0,2000,three,1165
1,13750,23,72937,Diesel,90,1.0,0,2000,3,1165
2,13950,24,41711,Diesel,90,NaN,0,2000,3,1165
3,14950,26,48000,Diesel,90,0.0,0,2000,3,1165
4,13750,30,38500,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,56,20544,Petrol,86,1.0,0,1300,3,1025
1432,10845,72,??,Petrol,86,0.0,0,1300,3,1015
1433,8500,56,17016,Petrol,86,0.0,0,1300,3,1015
1434,7250,70,??,NaN,86,1.0,0,1300,3,1015
1435,6950,76,1,Petrol,110,0.0,0,1600,5,1114

km handle

In [107]:
#handle ??
data["KM"] = (data["KM"].replace("??",np.nan)).astype(dtype="Int64")
data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23,46986,Diesel,90,1.0,0,2000,three,1165
1,13750,23,72937,Diesel,90,1.0,0,2000,3,1165
2,13950,24,41711,Diesel,90,NaN,0,2000,3,1165
3,14950,26,48000,Diesel,90,0.0,0,2000,3,1165
4,13750,30,38500,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,56,20544,Petrol,86,1.0,0,1300,3,1025
1432,10845,72,<NA>,Petrol,86,0.0,0,1300,3,1015
1433,8500,56,17016,Petrol,86,0.0,0,1300,3,1015
1434,7250,70,<NA>,NaN,86,1.0,0,1300,3,1015
1435,6950,76,1,Petrol,110,0.0,0,1600,5,1114

In [108]:
data["KM"] = data["KM"].fillna(value=data["KM"].mean().__round__())
data["KM"]

0       46986
1       72937
2       41711
3       48000
4       38500
        ...
1431    20544
1432    68647
1433    17016
1434    68647
1435        1
Name: KM, Length: 1436, dtype: Int64

metcolor handle

In [109]:

data["MetColor"] = data["MetColor"].fillna(value=data["MetColor"].mode()[0]).astype("Int8")
data["MetColor"]

0       1
1       1
2       1
3       0
4       0
       ..
1431    1
1432    0
1433    0
1434    1
1435    0
Name: MetColor, Length: 1436, dtype: Int8

handle fueltype

In [110]:
data["FuelType"] = data["FuelType"].fillna(value=data["FuelType"].mode()[0])
data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23,46986,Diesel,90,1,0,2000,three,1165
1,13750,23,72937,Diesel,90,1,0,2000,3,1165
2,13950,24,41711,Diesel,90,1,0,2000,3,1165
3,14950,26,48000,Diesel,90,0,0,2000,3,1165
4,13750,30,38500,Diesel,90,0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,56,20544,Petrol,86,1,0,1300,3,1025
1432,10845,72,68647,Petrol,86,0,0,1300,3,1015
1433,8500,56,17016,Petrol,86,0,0,1300,3,1015
1434,7250,70,68647,Petrol,86,1,0,1300,3,1015
1435,6950,76,1,Petrol,110,0,0,1600,5,1114

handle hp

In [111]:
data["HP"] = data["HP"].replace("????",np.nan).astype(dtype="Int16")
data["HP"] = data["HP"].fillna(value=data["HP"].mean().__round__())
data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23,46986,Diesel,90,1,0,2000,three,1165
1,13750,23,72937,Diesel,90,1,0,2000,3,1165
2,13950,24,41711,Diesel,90,1,0,2000,3,1165
3,14950,26,48000,Diesel,90,0,0,2000,3,1165
4,13750,30,38500,Diesel,90,0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,56,20544,Petrol,86,1,0,1300,3,1025
1432,10845,72,68647,Petrol,86,0,0,1300,3,1015
1433,8500,56,17016,Petrol,86,0,0,1300,3,1015
1434,7250,70,68647,Petrol,86,1,0,1300,3,1015
1435,6950,76,1,Petrol,110,0,0,1600,5,1114

handle door

In [112]:
word_to_num = {
  "one" : 1,
  "two" : 2,
  "three" : 3,
  "four" : 4,
  "five" : 5,
  "six": 6,
  "seven": 7,
  "eight" : 8,
  "nine" : 9
}

def transform_word_to_num(x:str|int)->int :
  if isinstance(x,str) and x.lower().strip() in word_to_num:
    return (word_to_num[x])
  return (int)(x)


data["Doors"] = data["Doors"].apply(transform_word_to_num)

In [113]:
data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23,46986,Diesel,90,1,0,2000,3,1165
1,13750,23,72937,Diesel,90,1,0,2000,3,1165
2,13950,24,41711,Diesel,90,1,0,2000,3,1165
3,14950,26,48000,Diesel,90,0,0,2000,3,1165
4,13750,30,38500,Diesel,90,0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,56,20544,Petrol,86,1,0,1300,3,1025
1432,10845,72,68647,Petrol,86,0,0,1300,3,1015
1433,8500,56,17016,Petrol,86,0,0,1300,3,1015
1434,7250,70,68647,Petrol,86,1,0,1300,3,1015
1435,6950,76,1,Petrol,110,0,0,1600,5,1114

### categorical data

In [114]:
data = pd.get_dummies(data=data, columns=["FuelType"],  dtype="int")
data

,Price,Age,KM,HP,MetColor,Automatic,CC,Doors,Weight,FuelType_CNG,FuelType_Diesel,FuelType_Petrol
0,13500,23,46986,90,1,0,2000,3,1165,0,1,0
1,13750,23,72937,90,1,0,2000,3,1165,0,1,0
2,13950,24,41711,90,1,0,2000,3,1165,0,1,0
3,14950,26,48000,90,0,0,2000,3,1165,0,1,0
4,13750,30,38500,90,0,0,2000,3,1170,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1431,7500,56,20544,86,1,0,1300,3,1025,0,0,1
1432,10845,72,68647,86,0,0,1300,3,1015,0,0,1
1433,8500,56,17016,86,0,0,1300,3,1015,0,0,1
1434,7250,70,68647,86,1,0,1300,3,1015,0,0,1
1435,6950,76,1,110,0,0,1600,5,1114,0,0,1

### scaling

In [115]:
from sklearn.preprocessing import StandardScaler

sscaler = StandardScaler()
cols = ["Age", "KM", "HP", "CC", "Doors", "Weight"]

sc = sscaler.fit_transform(data[cols])

df = pd.DataFrame(sc, columns=cols)

data[cols] = df

data

,Price,Age,KM,HP,MetColor,Automatic,CC,Doors,Weight,FuelType_CNG,FuelType_Diesel,FuelType_Petrol
0,13500,-1.824056,-0.583476,-0.778993,1,0,2.314976,-1.085139,1.758561,0,1,0
1,13750,-1.824056,0.115551,-0.778993,1,0,2.314976,-1.085139,1.758561,0,1,0
2,13950,-1.768266,-0.725566,-0.778993,1,0,2.314976,-1.085139,1.758561,0,1,0
3,14950,-1.656686,-0.556163,-0.778993,0,0,2.314976,-1.085139,1.758561,0,1,0
4,13750,-1.433526,-0.812059,-0.778993,0,0,2.314976,-1.085139,1.853577,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1431,7500,0.017017,-1.295729,-1.050507,1,0,-1.425994,-1.085139,-0.901883,0,0,1
1432,10845,0.909658,-0.000006,-1.050507,0,0,-1.425994,-1.085139,-1.091915,0,0,1
1433,8500,0.017017,-1.390761,-1.050507,0,0,-1.425994,-1.085139,-1.091915,0,0,1
1434,7250,0.798078,-0.000006,-1.050507,1,0,-1.425994,-1.085139,-1.091915,0,0,1
1435,6950,1.132819,-1.849084,0.578573,0,0,0.177279,1.014941,0.789399,0,0,1

In [116]:
data.to_csv("pre-proccesed-data.csv", index=False)