In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':10,'b':20,'c':30}

In [4]:
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(data=labels)
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [9]:
ser1=pd.Series([1,2,3,4],['usa','ger','ussr','jap'])
ser1

usa     1
ger     2
ussr    3
jap     4
dtype: int64

In [10]:
ser2=pd.Series([1,2,5,4],['usa','ger','ita','jap'])
ser2

usa    1
ger    2
ita    5
jap    4
dtype: int64

In [11]:
ser1['usa']

np.int64(1)

In [12]:
ser3=pd.Series(data=labels)
ser3[0]

'a'

In [13]:
ser1+ser2

ger     4.0
ita     NaN
jap     8.0
usa     2.0
ussr    NaN
dtype: float64